# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure-cpg-test'
    subscriptionId: '29c1ad9f-091e-48a2-9184-01a489833f34'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'cpg-dnd'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/valarmathi/azure-arm/main/CreateWebApp/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DevopsVM'
    overrideParameters: '-projectName azurevalar -adminUsername ValarVM -authenticationType password -adminPasswordOrKey SnowUser@2022!Galaxy'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
