# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Cloud Management Azure Subscrption'
    subscriptionId: '29c1ad9f-091e-48a2-9184-01a489833f34'
    action: 'create or update resource group'
    resourceGroupName: 'azurePipeline-rm'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://dev.azure.com/valarmathikannan0219/valarmathikannan/_git/azure-arm-repo?path=/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName azure-arm-repo'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployArmTemplate'
